image: maven:3-jdk-11

stages:
  - build
  - dockerize
  - tag

cache:
  paths:
    - .m2/

build:
  stage: build
  script:
    - mvn clean package spring-boot:repackage -DskipTests
  artifacts:
    paths:
      - target/*.jar

dockerize:
  image: docker:latest
  stage: dockerize
  services:
    - docker:dind
  script:
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker build -t $DOCKER_HUB_USERNAME/external-server:$CI_COMMIT_TAG .
    - docker push $DOCKER_HUB_USERNAME/external-server:$CI_COMMIT_TAG
    - docker tag $DOCKER_HUB_USERNAME/external-server:$CI_COMMIT_TAG $DOCKER_HUB_USERNAME/external-server:latest
    - docker push $DOCKER_HUB_USERNAME/external-server:latest
  only:
    - tags

tag:
  stage: tag
  script:
    - 'if [[ "$CI_COMMIT_REF_NAME" == "development" ]] && [[ "$(git log --format=%B -n 1)" =~ ^(\w+)(\(\w+\))?:\s(.*)$ ]]; then ./create_tag.sh; fi'
  only:
    - branches
