spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
keycloak:
  serverUrl: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM:master}
  clientId: ${KEYCLOAK_CLIENT_ID:admin-cli}
  username: ${KEYCLOAK_ADMIN}
  password: ${KEYCLOAK_ADMIN_PASSWORD}
server:
  port: 8000

---

spring:
  profiles: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

---

spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
