version: '3'

services:
  server:
    image: external-server:latest
    container_name: external-server
    restart: unless-stopped   # Restart policy for the server service
    environment:
      SPRING_PROFILES_ACTIVE: postgres,docker
      KEYCLOAK_SERVER_URL: http://127.0.0.1:8080/auth
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./localhost.p12:/etc/ssl/certs/ssl.p12
    ports:
      - "8000:8080"
      - "8444:8443"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13.2
    container_name: postgres
    restart: unless-stopped   # Restart policy for the postgres service
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
