version: '3'

services:
  server:
    image: datpd2402/external-server:2.0.12
    container_name: external-server
    command: /app/start-app.sh
    extra_hosts:
      - "keycloak-utm.com:192.168.48.7"
    restart: unless-stopped   # Restart policy for the server service
    environment:
      SPRING_PROFILES_ACTIVE: postgres,docker
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../x509/manage.com.p12:/etc/ssl/certs/ssl.p12
      - ../x509/rootCA.crt:/var/ssl/rootCA.crt
    ports:
      - "8080"
      - "8443"
    depends_on:
      - postgres
    networks:
      - app-network
      - my-network  # Add this line

  postgres:
    image: postgres:13.2
    container_name: postgres
    restart: unless-stopped   # Restart policy for the postgres service
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
      - my-network  # Add this line

networks:
  app-network:
  my-network: # And add these two lines
    external: true
